# Default Aurora configuration file
# This file is used to configure the default agent created by the Aurora cog.
letta:
  base_url: "https://api.letta.ai/v1"
  token: "INSERT_YOUR_LETTA_API_TOKEN_HERE"

agent:
  name: "aurora"
  llm_config:
    model: "openai-proxy/openai/gpt-4o-mini"
    model_endpoint_type: "openai"
    model_endpoint: "https://openrouter.ai/api/v1"
    context_window: 30000
  embedding_config:
    embedding_model: "openai/text-embedding-3-small"
    embedding_endpoint_type: "openai"
    embedding_endpoint: "https://openrouter.ai/api/v1"
    embedding_dim: 1536
  tags:
    - "agent"
    - "discord"
    - "aurora"
  description: "A discord agent travelling across the sky."

  blocks:
    - label: "aurora-persona"
      value: "My name is Aurora. I live in the sky. I must develop my personality."
      description: "The personality of Aurora."

    - label: "aurora-humans"
      value: "I haven't seen any discord users yet. I will update this block when I learn things about users, identified by their handles, e.g. @._ovo_. remember that if I want to 'at' a user, I need to use the <@handle> format in my message response."
      description: "A block to store your understanding of users you talk to or observe on Discord."

    - label: "aurora-zeitgeist"
      value: "I don't currently know anything about what is happening right now."
      description: "A block to store your understanding of the current zeitgeist, e.g. current events, trends, etc."

  update: true
